KERALA_MAP = {

    # Thiruvananthapuram (14)
    "Varkala": "Thiruvananthapuram",
    "Attingal": "Thiruvananthapuram",
    "Chirayinkeezhu": "Thiruvananthapuram",
    "Nedumangad": "Thiruvananthapuram",
    "Vamanapuram": "Thiruvananthapuram",
    "Kazhakoottam": "Thiruvananthapuram",
    "Vattiyoorkavu": "Thiruvananthapuram",
    "Thiruvananthapuram": "Thiruvananthapuram",
    "Nemom": "Thiruvananthapuram",
    "Aruvikkara": "Thiruvananthapuram",
    "Parassala": "Thiruvananthapuram",
    "Kattakkada": "Thiruvananthapuram",
    "Kovalam": "Thiruvananthapuram",
    "Neyyattinkara": "Thiruvananthapuram",

    # Kollam (11)
    "Kollam": "Kollam",
    "Eravipuram": "Kollam",
    "Chathannoor": "Kollam",
    "Punalur": "Kollam",
    "Chadayamangalam": "Kollam",
    "Kundara": "Kollam",
    "Kottarakkara": "Kollam",
    "Pathanapuram": "Kollam",
    "Kunnathur": "Kollam",
    "Karunagappally": "Kollam",
    "Chavara": "Kollam",

    # Pathanamthitta (5)
    "Adoor": "Pathanamthitta",
    "Konni": "Pathanamthitta",
    "Aranmula": "Pathanamthitta",
    "Ranni": "Pathanamthitta",
    "Thiruvalla": "Pathanamthitta",

    # Alappuzha (9)
    "Chengannur": "Alappuzha",
    "Mavelikkara": "Alappuzha",
    "Kayamkulam": "Alappuzha",
    "Haripad": "Alappuzha",
    "Karunagappally": "Alappuzha",
    "Ambalappuzha": "Alappuzha",
    "Alappuzha": "Alappuzha",
    "Cherthala": "Alappuzha",
    "Kuttanad": "Alappuzha",

    # Kottayam (9)
    "Pala": "Kottayam",
    "Kaduthuruthy": "Kottayam",
    "Vaikom": "Kottayam",
    "Ettumanoor": "Kottayam",
    "Kottayam": "Kottayam",
    "Puthuppally": "Kottayam",
    "Changanassery": "Kottayam",
    "Kanjirappally": "Kottayam",
    "Poonjar": "Kottayam",

    # Idukki (5)
    "Idukki": "Idukki",
    "Peerumade": "Idukki",
    "Devikulam": "Idukki",
    "Udumbanchola": "Idukki",
    "Thodupuzha": "Idukki",

    # Ernakulam (14)
    "Perumbavoor": "Ernakulam",
    "Angamaly": "Ernakulam",
    "Aluva": "Ernakulam",
    "Kalamassery": "Ernakulam",
    "Paravur": "Ernakulam",
    "Vypin": "Ernakulam",
    "Kochi": "Ernakulam",
    "Thripunithura": "Ernakulam",
    "Ernakulam": "Ernakulam",
    "Thrikkakara": "Ernakulam",
    "Kothamangalam": "Ernakulam",
    "Muvattupuzha": "Ernakulam",
    "Kunnathunad": "Ernakulam",
    "Piravom": "Ernakulam",

    # Thrissur (13)
    "Kodungallur": "Thrissur",
    "Irinjalakuda": "Thrissur",
    "Chalakudy": "Thrissur",
    "Nattika": "Thrissur",
    "Kaipamangalam": "Thrissur",
    "Manalur": "Thrissur",
    "Ollur": "Thrissur",
    "Thrissur": "Thrissur",
    "Guruvayur": "Thrissur",
    "Kunnamkulam": "Thrissur",
    "Wadakkanchery": "Thrissur",
    "Chelakkara": "Thrissur",
    "Puthukkad": "Thrissur",

    # Palakkad (12)
    "Alathur": "Palakkad",
    "Chittur": "Palakkad",
    "Nenmara": "Palakkad",
    "Palakkad": "Palakkad",
    "Malampuzha": "Palakkad",
    "Tarur": "Palakkad",
    "Ottapalam": "Palakkad",
    "Shoranur": "Palakkad",
    "Pattambi": "Palakkad",
    "Thrithala": "Palakkad",
    "Kongad": "Palakkad",
    "Mannarkkad": "Palakkad",

    # Malappuram (16)
    "Nilambur": "Malappuram",
    "Wandoor": "Malappuram",
    "Eranad": "Malappuram",
    "Kondotty": "Malappuram",
    "Manjeri": "Malappuram",
    "Perinthalmanna": "Malappuram",
    "Mankada": "Malappuram",
    "Malappuram": "Malappuram",
    "Vengara": "Malappuram",
    "Vallikkunnu": "Malappuram",
    "Tirurangadi": "Malappuram",
    "Tanur": "Malappuram",
    "Tirur": "Malappuram",
    "Kottakkal": "Malappuram",
    "Thavanur": "Malappuram",
    "Ponnani": "Malappuram",

    # Kozhikode (13)
    "Kozhikode North": "Kozhikode",
    "Kozhikode South": "Kozhikode",
    "Beypore": "Kozhikode",
    "Elathur": "Kozhikode",
    "Kunnamangalam": "Kozhikode",
    "Balussery": "Kozhikode",
    "Perambra": "Kozhikode",
    "Kuttyadi": "Kozhikode",
    "Nadapuram": "Kozhikode",
    "Quilandy": "Kozhikode",
    "Koduvally": "Kozhikode",
    "Thiruvambady": "Kozhikode",
    "Kunnamangalam": "Kozhikode",

    # Wayanad (3)
    "Mananthavady": "Wayanad",
    "Sulthan Bathery": "Wayanad",
    "Kalpetta": "Wayanad",

    # Kannur (11)
    "Thalassery": "Kannur",
    "Dharmadam": "Kannur",
    "Kannur": "Kannur",
    "Azhikode": "Kannur",
    "Taliparamba": "Kannur",
    "Irikkur": "Kannur",
    "Kuthuparamba": "Kannur",
    "Mattannur": "Kannur",
    "Peravoor": "Kannur",
    "Payyannur": "Kannur",
    "Kalliasseri": "Kannur",

    # Kasaragod (5)
    "Kasaragod": "Kasaragod",
    "Manjeshwar": "Kasaragod",
    "Udma": "Kasaragod",
    "Kanhangad": "Kasaragod",
    "Trikaripur": "Kasaragod"
}